export let comidas = [
  {
    id: 1,
    name: "Un cuarto de pollo",
    description: "1/4 de pollo + papas + ensalada + cremas",
    price: 17,
    isDiscount: 10,
    images: "un-cuarto.webp",
    category: "personales",
  },
  {
    id: 2,
    name: "Medio pollo",
    description: "1/2 de pollo + papas + ensalada + cremas",
    price: 30,
    isDiscount: 0,
    images: "medio-pollo.webp",
    category: "duplas",
  },
  {
    id: 3,
    name: "Un pollo",
    description: "1 pollo entero + papas + ensalada + cremas",
    price: 54,
    isDiscount: 0,
    images: "un-pollo.webp",
    category: "familiares",
  },
  {
    id: 4,
    name: "Un cuarto broaster",
    description: "1/4 de pollo broaster + papas + ensalada + cremas",
    price: 20,
    isDiscount: 0,
    images: "broster-cuarto-de-pollo.webp",
    category: "broaster",
  },
  {
    id: 5,
    name: "Medio broaster",
    description: "1/2 de pollo broaster + papas + ensalada + cremas",
    price: 36,
    isDiscount: 10,
    images: "broster-medio-pollo.webp",
    category: "broaster",
  },
  {
    id: 6,
    name: "Un pollo broaster",
    description: "1 pollo broaster entero + papas + ensalada + cremas",
    price: 60,
    isDiscount: 0,
    images: "broster-pollo-entero.webp",
    category: "broaster",
  },
  {
    id: 7,
    name: "Mostrito octavo",
    description: "1/8 de pollo + papas + arroz chaufa + ensalada + cremas",
    price: 15,
    isDiscount: 0,
    images: "mostrito-octavo.webp",
    category: "mostritos",
  },
  {
    id: 8,
    name: "Mostrito cuarto",
    description: "1/4 de pollo + papas + arroz chaufa + ensalada + cremas",
    price: 22,
    isDiscount: 0,
    images: "mostrito-cuarto.webp",
    category: "mostritos",
  },
  {
    id: 9,
    name: "Mostrito broaster",
    description:
      "1/4 de pollo broaster + papas + arroz chaufa + ensalada + cremas",
    price: 24,
    isDiscount: 5,
    images: "mostrito-broster.webp",
    category: "mostritos",
  },
  {
    id: 10,
    name: "Inka Cola personal",
    description: "Bebida",
    price: 3,
    isDiscount: 0,
    images: "inkacola-personal.webp",
    category: "bebidas",
  },
  {
    id: 11,
    name: "Inka Cola 1L",
    description: "Bebida",
    price: 6,
    isDiscount: 0,
    images: "inkacola-un-litro.webp",
    category: "bebidas",
  },
  {
    id: 12,
    name: "Inka Cola 1.5L",
    description: "Bebida",
    price: 8,
    isDiscount: 0,
    images: "inkacola-un-litro.webp",
    category: "bebidas",
  },
  {
    id: 13,
    name: "Chicha morada 1L",
    description: "Bebida",
    price: 8,
    isDiscount: 0,
    images: "chicha.webp",
    category: "bebidas",
  },
];